######################################################################
# conan-singlePlatform.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow will install Conan dependencies, build the selected
# tool, and deliver the package to artifact management
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
# - https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html
#

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths

name: Conan C/C++ single platform CI

on:
  workflow_call:
    inputs:
      runner_selection:
        type: string
        default: self-hosted
      container_image:
        type: string
        default: 'ubuntu:latest'
      conan_profile:
        type: string
        default:
      is_enabled:
        type: boolean
        default: true

jobs:
  conan_build:
    if: ${{ inputs.is_enabled }}
    runs-on: ${{ inputs.runner_selection }}
    container:
      image: ${{ inputs.container_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

#    - name: Install and setup Conan
#      uses: conan-io/setup-conan@v1
#      with:
#        audit_token: ${{ secrets.MY_CONAN_AUDIT_TOKEN }}

    - name: Install Conan profiles
      run: |
        echo conan config install .

    - name: Scan for vulnerabilities with Conan Audit
      run: |
        echo conan audit scan .

    - name: Conan Source
      run: |
        echo conan source .

    - name: Conan Install
      run: |
        echo conan install .

    - name: Conan Build
      run: |
        echo conan build .

    - name: Conan Packaging
      run: |
        echo conan export-pkg .

    - name: Conan Test
      run: |
        echo conan test .

#    - name: Build and upload package
#      run: |
#        conan create . -pr:a myprofile --build=missing
#        conan remote login artifactory developer -p ${{ secrets.MY_CONAN_PASSWORD }}
#        conan upload "*" --confirm --remote artifactory