######################################################################
# conan-demoToolchain.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow calls the conan-multiPlatformToolchain.yml workflow
# for our demo toolchain.
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
#

name: Demo Phased Toolchain build

on:
  workflow_dispatch:
    inputs:
      runner_selection:
        type: string
        default: self-hosted
      conan_recipe_remote:
        type: string
        default: "./conan-center-index"  # We provide this as a git submodule since we use a non-default branch
      toolchain_prefix:
        type: string
        default: "/opt/toolchain"
      ubuntu-aarch64-enabled:
        type: boolean
        default: false
      ubuntu-x86_64-enabled:
        type: boolean
        default: false
      almalinux-aarch64-enabled:
        type: boolean
        default: false
      almalinux-x86_64-enabled:
        type: boolean
        default: false

jobs:
  toolchain_phase1:
    uses: ./.github/workflows/conan-multiPlatformToolchain.yml
    secrets: inherit
    with:
      component_subdirectory: "components/phase1"
      save_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      runner_selection: ${{ inputs.runner_selection }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-almalinux:x86_64-latest"

  #TODO provide and install the packages generated by phase 1 to phase 2
  toolchain_phase2:
    uses: ./.github/workflows/conan-multiPlatformToolchain.yml
    secrets: inherit
    needs: toolchain_phase1
    with:
      component_subdirectory: "components/phase2"
      restore_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      runner_selection: ${{ inputs.runner_selection }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "ghcr.io/daversomethingsomethingorg/bootstrap-almalinux:x86_64-latest"

  #TODO provide and install the packages generated by phases 1 and 2 to phase 3
  toolchain_phase3:
    uses: ./.github/workflows/conan-multiPlatformToolchain.yml
    secrets: inherit
    needs: toolchain_phase2
    with:
      component_subdirectory: "components/phase3"
      restore_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase3-${{ github.run_id }}"
      runner_selection: ${{ inputs.runner_selection }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
