######################################################################
# conan-demo.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow calls the conan-multiPlatform.yml workflow for our
# demo toolchain.
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
#

name: Demo

on:
  workflow_dispatch:
    inputs:
      runner_selection:
        type: string
        default: self-hosted
      ubuntu-aarch64-enabled:
        type: boolean
        default: false
      ubuntu-x86_64-enabled:
        type: boolean
        default: false
      almalinux-aarch64-enabled:
        type: boolean
        default: true
      almalinux-x86_64-enabled:
        type: boolean
        default: false

jobs:
  demo_multi_platform:
    uses: ./.github/workflows/conan-multiPlatform.yml
    secrets: inherit
    with:
      runner_selection: ${{ inputs.runner_selection }}
      ubuntu-aarch64-enabled: ${{ inputs.ubuntu-aarch64-enabled }}
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      almalinux-aarch64-enabled: ${{ inputs.almalinux-aarch64-enabled }}
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      