######################################################################
# conan-multiPlatform.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow will optionally run the conan-singlePlatform.yml workflow
# across a list of selected platforms.
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
#

name: Conan C/C++ multi-platform Toolchain

on:
  workflow_call:
    inputs:
      runner_selection:
        type: string
        default: self-hosted
      component_subdirectory:
        type: string
        default: "src"
      conan_recipe_remote:
        type: string
      toolchain_prefix:
        type: string
        required: true
      ubuntu-aarch64-enabled:
        type: boolean
        default: true
      ubuntu-aarch64-image:
        type: string
        default: "ghcr.io/daversomethingsomethingorg/conan-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled:
        type: boolean
        default: false
      ubuntu-x86_64-image:
        type: string
        default: "ghcr.io/daversomethingsomethingorg/conan-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled:
        type: boolean
        default: true
      almalinux-aarch64-image:
        type: string
        default: "ghcr.io/daversomethingsomethingorg/conan-almalinux:aarch64-latest"
      almalinux-x86_64-enabled:
        type: boolean
        default: false
      almalinux-x86_64-image:
        type: string
        default: "ghcr.io/daversomethingsomethingorg/conan-almalinux:x86_64-latest"

jobs:
  conan_mp_toolchain:
    name: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - platform: "ubuntu-aarch64"
            container_image: ${{ inputs.ubuntu-aarch64-image }}
            is_enabled: ${{ inputs.ubuntu-aarch64-enabled }}
            conan_deployer: 'deb_deployer'
          - platform: "ubuntu-x86_64"
            container_image: ${{ inputs.ubuntu-x86_64-image }}
            is_enabled: ${{ inputs.ubuntu-x86_64-enabled }}
            conan_deployer: 'deb_deployer'
          - platform: "almalinux-aarch64"
            container_image: ${{ inputs.almalinux-aarch64-image }}
            is_enabled: ${{ inputs.almalinux-aarch64-enabled }}
            conan_deployer: 'rpm_deployer'
          - platform: "almalinux-x86_64"
            container_image: ${{ inputs.almalinux-x86_64-image }}
            is_enabled: ${{ inputs.almalinux-x86_64-enabled }}
            conan_deployer: 'rpm_deployer'
    uses: ./.github/workflows/conan-toolchain.yml
    secrets: inherit
    with:
      runner_selection: ${{ inputs.runner_selection }}
      component_subdirectory: ${{ inputs.component_subdirectory }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      container_image: ${{ matrix.container_image }}
      is_enabled: ${{ matrix.is_enabled }}
      conan_deployer: ${{ matrix.conan_deployer }}
